// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WPST.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220314002047_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bodovi")
                        .HasColumnType("int");

                    b.Property<int>("Broj_Legitimacije")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("Datumrodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Klub_ID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Turnir_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Turnir_ID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Klub_ID");

                    b.HasIndex("Turnir_ID");

                    b.HasIndex("Turnir_ID1");

                    b.ToTable("Igrac");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Property<int>("Klub_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojIgraca")
                        .HasColumnType("int");

                    b.Property<string>("ImeKluba")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MestoKluba")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Klub_ID");

                    b.ToTable("Klubovi");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Property<int>("Mec_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Igrac1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Igrac2ID")
                        .HasColumnType("int");

                    b.Property<int>("Kolo")
                        .HasColumnType("int");

                    b.Property<int>("Rezultat_Ishod")
                        .HasColumnType("int");

                    b.Property<int>("Turnir_ID")
                        .HasColumnType("int");

                    b.HasKey("Mec_ID");

                    b.HasIndex("Igrac1ID");

                    b.HasIndex("Igrac2ID");

                    b.HasIndex("Turnir_ID");

                    b.ToTable("Mec");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Property<int>("Sudija_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Klasa")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Sudija_ID");

                    b.ToTable("Sudija");
                });

            modelBuilder.Entity("Models.Turnir", b =>
                {
                    b.Property<int>("Turnir_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum_pocetka")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime_Turnira")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mesto_Odrzavanja")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Nagrada")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int?>("OrganizatorTurniraKlub_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Osvajac_TurniraID")
                        .HasColumnType("int");

                    b.Property<int?>("Sudija_ID")
                        .HasColumnType("int");

                    b.HasKey("Turnir_ID");

                    b.HasIndex("OrganizatorTurniraKlub_ID");

                    b.HasIndex("Osvajac_TurniraID");

                    b.HasIndex("Sudija_ID");

                    b.ToTable("Turnir");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.HasOne("Models.Klub", "Klub")
                        .WithMany("Igraci")
                        .HasForeignKey("Klub_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Turnir", null)
                        .WithMany("Ostali_igraci")
                        .HasForeignKey("Turnir_ID");

                    b.HasOne("Models.Turnir", null)
                        .WithMany("Prijavljeni_igraci")
                        .HasForeignKey("Turnir_ID1");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.HasOne("Models.Igrac", "Igrac1")
                        .WithMany()
                        .HasForeignKey("Igrac1ID");

                    b.HasOne("Models.Igrac", "Igrac2")
                        .WithMany()
                        .HasForeignKey("Igrac2ID");

                    b.HasOne("Models.Turnir", "Turnir")
                        .WithMany("Mecevi")
                        .HasForeignKey("Turnir_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igrac1");

                    b.Navigation("Igrac2");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("Models.Turnir", b =>
                {
                    b.HasOne("Models.Klub", "OrganizatorTurnira")
                        .WithMany()
                        .HasForeignKey("OrganizatorTurniraKlub_ID");

                    b.HasOne("Models.Igrac", "Osvajac_Turnira")
                        .WithMany()
                        .HasForeignKey("Osvajac_TurniraID");

                    b.HasOne("Models.Sudija", "Sudija")
                        .WithMany("Sudjeni_turniri")
                        .HasForeignKey("Sudija_ID");

                    b.Navigation("OrganizatorTurnira");

                    b.Navigation("Osvajac_Turnira");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Navigation("Igraci");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Navigation("Sudjeni_turniri");
                });

            modelBuilder.Entity("Models.Turnir", b =>
                {
                    b.Navigation("Mecevi");

                    b.Navigation("Ostali_igraci");

                    b.Navigation("Prijavljeni_igraci");
                });
#pragma warning restore 612, 618
        }
    }
}
